export const cardImages =
    [
        [
            { "src": '/images/memory-game-card_1.jpg', "matched": false },
            { "src": '/images/memory-game-card_2.jpg', "matched": false },
            { "src": '/images/memory-game-card_3.jpg', "matched": false },
            { "src": '/images/memory-game-card_4.jpg', "matched": false },
            { "src": '/images/memory-game-card_5.jpg', "matched": false },
            { "src": '/images/memory-game-card_6.jpg', "matched": false },
        ],
        [
            { "src": '/images/memory-game-card_7.jpg', "matched": false },
            { "src": '/images/memory-game-card_8.jpg', "matched": false },
            { "src": '/images/memory-game-card_9.jpg', "matched": false },
            { "src": '/images/memory-game-card_10.jpg', "matched": false },
            { "src": '/images/memory-game-card_11.jpg', "matched": false },
            { "src": '/images/memory-game-card_12.jpg', "matched": false },
        ],
        [
            { "src": '/images/memory-game-card_13.jpg', "matched": false },
            { "src": '/images/memory-game-card_14.jpg', "matched": false },
            { "src": '/images/memory-game-card_15.jpg', "matched": false },
            { "src": '/images/memory-game-card_16.jpg', "matched": false },
            { "src": '/images/memory-game-card_17.jpg', "matched": false },
            { "src": '/images/memory-game-card_18.jpg', "matched": false },
        ],
        [
            { "src": '/images/memory-game-card_19.jpg', "matched": false },
            { "src": '/images/memory-game-card_20.jpg', "matched": false },
            { "src": '/images/memory-game-card_21.jpg', "matched": false },
            { "src": '/images/memory-game-card_22.jpg', "matched": false },
            { "src": '/images/memory-game-card_23.jpg', "matched": false },
            { "src": '/images/memory-game-card_24.jpg', "matched": false },
        ],
        [
            { "src": '/images/memory-game-card_25.jpg', "matched": false },
            { "src": '/images/memory-game-card_26.jpg', "matched": false },
            { "src": '/images/memory-game-card_27.jpg', "matched": false },
            { "src": '/images/memory-game-card_28.jpg', "matched": false },
            { "src": '/images/memory-game-card_29.jpg', "matched": false },
            { "src": '/images/memory-game-card_30.jpg', "matched": false },
        ],
        [
            { "src": '/images/memory-game-card_31.jpg', "matched": false },
            { "src": '/images/memory-game-card_32.jpg', "matched": false },
            { "src": '/images/memory-game-card_33.jpg', "matched": false },
            { "src": '/images/memory-game-card_34.jpg', "matched": false },
            { "src": '/images/memory-game-card_35.jpg', "matched": false },
            { "src": '/images/memory-game-card_36.jpg', "matched": false },
        ],
    ]